[[step]]
mode = 12  # 控制模式
gait_id = 0  # 步态ID
contact = 0  # 接触状态
life_count = 0  # 生命周期计数 (虚拟值)
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.0]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 5000  # 预期的执行时间 (位置插值控制需要大于5.0秒)

[[step]]
mode = 21  # 位置插值控制
gait_id = 5  # 步态ID
contact = 15  # 接触状态 (0b00001111 : 四条腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.15]  # 期望的位置，z表示绝对重心高度
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 300  # 持续时间

[[step]]
mode = 21  # 位置插值控制
gait_id = 5  # 步态ID
contact = 15  # 接触状态 (四条腿接触)
life_count = 0  # 生命周期计数
value = 0  # 其他值
duration = 400  # 持续时间
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.25]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高

[[step]]
mode = 21  # 位置插值控制
gait_id = 0  # 步态ID
contact = 15  # 接触状态 (四条腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, -0.25, 0.0]  # 期望的滚转、俯仰、偏航角 (roll, pitch, yaw)
pos_des = [0.05, 0.05, -0.0]  # 期望的位置 (x, y, z), 右手坐标系, +X:前, +Y:左, +Z:上
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.1, 0.0, 0.0]  # 控制点坐标 (x, y, z)
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 500  # 持续时间

[[step]]
mode = 21  # 位置插值控制
gait_id = 0  # 步态ID
contact = 11  # 接触状态 (0b00001011 : 后右腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.0]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [-0.1, -0.1, 0.15, 0.0, 0.0, 0.0]  # 提脚沿坐标轴移动距离 (x, y, z)
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 500  # 持续时间

[[step]]
mode = 21  # 位置插值控制
gait_id = 0  # 步态ID
contact = 11  # 接触状态 (后右腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.0]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 500  # 持续时间

[[step]]
mode = 21  # 位置插值控制
gait_id = 5  # 步态ID
contact = 15  # 接触状态 (四条腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.23]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 500  # 持续时间

[[step]]
mode = 11  # 运动控制
gait_id = 3  # 步态ID
contact = 15  # 接触状态 (四条腿接触)
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.5]  # 期望的x、y、偏航角速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.0]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.06, 0.06]  # 步高
value = 0  # 其他值
duration = 3000  # 持续时间

[[step]]
mode = 7  # 纯阻尼模式
gait_id = 0  # 步态ID
contact = 0  # 接触状态
life_count = 0  # 生命周期计数
vel_des = [0.0, 0.0, 0.0]  # 期望速度
rpy_des = [0.0, 0.0, 0.0]  # 期望的滚转、俯仰、偏航角
pos_des = [0.0, 0.0, 0.0]  # 期望的位置
acc_des = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的加速度
ctrl_point = [0.0, 0.0, 0.0]  # 控制点
foot_pose = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 足部姿态
step_height = [0.0, 0.0]  # 步高
value = 0  # 其他值
duration = 4000  # 持续时间
