# moonwalk步态参数

# 第1部分
[[step]]
type            = "usergait"  # 步态类型，用户自定义步态
body_vel_des    = [0.0, 0.0, 0.0]  # 期望的身体速度
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 期望的身体位置和姿态
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]  # 着陆位置
step_height     = [0.05, 0.01, 0.01, 0.05]  # 步态高度
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]  # 权重
use_mpc_traj    = 0  # 是否使用MPC轨迹
mu              = 0.40  # 摩擦系数
landing_gain    = 1.0  # 着陆增益
gait_id         = 110  # 步态ID
duration        = 300  # 持续时间

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

# 第2部分
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

# 第3部分
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

# 第4部分
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

# 第5部分
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  0.00, -0.00, 0.0,  0.00, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.065, 0.00, 0.0,  -0.065, -0.00, 0.0,  -0.065, 0.00, 0.0,  0.065, 0.00, 0.0]
step_height     = [0.05, 0.01, 0.01, 0.05]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.00, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  0.00, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.065, 0.00, 0.0,  0.065, -0.00, 0.0,  0.065, 0.00, 0.0,  -0.065, 0.00, 0.0]
step_height     = [0.01, 0.05, 0.05, 0.01]
weight          = [10.0, 10.0, 10.0, 50.0, 50.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0
gait_id         = 110
duration        = 240

# moonwalk结束



